#Show the ASCII banner when the plugin is enabled
ascii-banner: true

payments:
  #Pay a flat fee for each kill, or a percentage of the victim's balance
  flat-fee: false
  fee-amount: 100

  #Max 100
  percentage: 10

#Messages in the plugin, use the minimessage format(https://webui.advntr.dev/). If you have placeholderAPI enabled, you can use that too.
#Placeholders:
# - %victim% the person who was killed
# - %killer% the killer of the player
# - %amount% the amount earned.
messages:
  killer: "<gold>You killed <red>%victim%</red> and earned <red>%amount%</red></gold>"
  victim: "<red>You were killed by <gold>%killer%</gold> and lost <gold>%amount%</gold></red>"
